### ISSUE TITLE
infografia ciclos del software

### ISSUE THREAD

**Issue by Luisangelriverosbautista** [SistemasTecTlaxiaco/actividad-1-infografia-Luisangelriverosbautista#1]
[infofrafia ciclos.pdf](https://github.com/user-attachments/files/16770740/infofrafia.ciclos.pdf)

**Comment by Kim-Mendoza3** [comment]
Calificacion 18

**Comment by Angel-antonio03** [comment]
calificacion 18, diseño minimalista

**Comment by josealfredo79** [comment]
Bien  hecho y revisado..
